services:
  proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy-network

  ssl-generator:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=luisming96@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - proxy-network

  # 1. TU APP VITACLICK (Usabilidad)
  usabilidad:
    image: nginx:alpine
    container_name: usabilidad-container
    volumes:
      - /home/luismi/app_vitaclick/Estudio_de_usabilidad/pages:/usr/share/nginx/html:ro
      - /home/luismi/app_vitaclick/Estudio_de_usabilidad/assets:/usr/share/nginx/html/assets:ro
    environment:
      - VIRTUAL_HOST=usabilidad.luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=usabilidad.luismi.servidorgp.somosdelprieto.com
    networks:
      - proxy-network

  # 2. LANDING PAGE
  landing:
    image: luisming96/landing-page:latest
    container_name: landing-container
    environment:
      - VIRTUAL_HOST=luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=luismi.servidorgp.somosdelprieto.com
    networks:
      - proxy-network

  # 3. PORTAINER (Gestión)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - VIRTUAL_HOST=portainer-luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=portainer-luismi.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-network

  # 4. PROMETHEUS (Monitorización)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    environment:
      - VIRTUAL_HOST=prometheus-luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=prometheus-luismi.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=9090
    networks:
      - proxy-network

  # 5. GRAFANA (Métricas)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - VIRTUAL_HOST=grafana-luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=grafana-luismi.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

volumes:
  certs:
  vhost:
  html:
  acme:
  portainer_data:
  prometheus_data:
  grafana_data:
