version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - plataforma-network
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=luismi@ejemplo.com
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    depends_on:
      - nginx-proxy
    networks:
      - plataforma-network
    restart: always

  vitaclick:
    image: nginx:alpine
    container_name: usabilidad-container
    volumes:
      - ./vitaclick:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=usabilidad.luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=usabilidad.luismi.servidorgp.somosdelprieto.com
    networks:
      - plataforma-network
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - VIRTUAL_HOST=portainer.luismi.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.luismi.servidorgp.somosdelprieto.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - plataforma-network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - VIRTUAL_HOST=prometheus.luismi.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=prometheus.luismi.servidorgp.somosdelprieto.com
    networks:
      - plataforma-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - VIRTUAL_HOST=grafana.luismi.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.luismi.servidorgp.somosdelprieto.com
    networks:
      - plataforma-network
    restart: always

networks:
  plataforma-network:
    driver: bridge

volumes:
  portainer_data:
