services:
  proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy-network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    networks:
      - proxy-network

  usabilidad:
    image: nginx:alpine
    container_name: usabilidad-container
    restart: always
    volumes:
      - /home/luismi/app_vitaclick/Estudio_de_usabilidad/pages:/usr/share/nginx/html:ro
      - /home/luismi/app_vitaclick/Estudio_de_usabilidad/assets:/usr/share/nginx/html/assets:ro
    environment:
      - VIRTUAL_HOST=usabilidad.luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=usabilidad.luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_EMAIL=luisming96@gmail.com
    networks:
      - proxy-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=portainer-luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=portainer-luismi.servidorgp.somosdelprieto.com
      - LETSENCRYPT_EMAIL=luisming96@gmail.com
      - VIRTUAL_PORT=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network

volumes:
  certs:
  vhost:
  html:
  portainer_data:
